import type { ReservationSpec } from "@/modules/db/dev-seed/insert";

const PICKUP_PASSENGERS = [
  { domainId: "AJ29104", name: "Jimera, Arielle" },
  { domainId: "AM10394", name: "Dizon, Marco" },
];

const STANDBY_PASSENGERS = [
  { domainId: "AK47281", name: "Reyes, Kaye" },
  { domainId: "AM10394", name: "Dizon, Marco" },
  { domainId: "AL55210", name: "Salcedo, Liza" },
  { domainId: "AG80017", name: "Mateo, Angel" },
];

/** The instant the fixtures stamped on every admin-acted row. */
const ACTED_AT = "2026-08-04T09:20:00Z";
const MOBILE = "09567567122";

/**
 * The design document's own eight sample requests — the master list,
 * calendar, and manage views' canonical data, now seeded instead of fixtured.
 * References are issued chronologically at seed time, so the old REQ-#### ids
 * survive only as provenance keys here.
 */
export const CANONICAL_RESERVATIONS: readonly ReservationSpec[] = [
  {
    key: "REQ-1051",
    mode: "pickup",
    status: "Pending",
    site: "Iloilo",
    submittedAt: "2026-08-03T01:12:00Z",
    startDate: "2026-08-08",
    startTime: "06:30",
    endDate: null,
    endTime: null,
    requestor: "Jimera, Arielle",
    requestorMobile: MOBILE,
    purpose: "Travel-Related (Airport Transfers)",
    details: "Picking up a visiting auditor arriving on the 06:30 flight.",
    pickupLocation: "AGT Tower lobby",
    dropoffLocation: "GLS Building",
    towerHead: null,
    vendor: null,
    costPhp: null,
    passengers: PICKUP_PASSENGERS,
    driver: null,
    van: null,
    actedBy: null,
    actedAt: null,
    modified: true,
    rejectionReason: null,
    cancellationReason: null,
  },
  {
    key: "REQ-1049",
    mode: "pickup",
    status: "Approved",
    site: "Manila",
    submittedAt: "2026-08-01T02:40:00Z",
    startDate: "2026-08-07",
    startTime: "08:00",
    endDate: null,
    endTime: null,
    requestor: "Jimera, Arielle",
    requestorMobile: MOBILE,
    purpose: "Travel-Related (Airport Transfers)",
    details: "Dropping off a candidate for a 09:00 on-site interview.",
    pickupLocation: "GLS Tower lobby",
    dropoffLocation: "AGT Building",
    towerHead: null,
    vendor: null,
    costPhp: null,
    passengers: PICKUP_PASSENGERS,
    driver: "Villanueva, Rey",
    van: "VAN-001",
    actedBy: "Abanto, Norlyn",
    actedAt: ACTED_AT,
    modified: false,
    rejectionReason: null,
    cancellationReason: null,
  },
  {
    key: "REQ-1046",
    mode: "pickup",
    status: "Cancelled",
    site: "Manila",
    submittedAt: "2026-07-29T06:05:00Z",
    startDate: "2026-08-06",
    startTime: "09:00",
    endDate: null,
    endTime: null,
    requestor: "Jimera, Arielle",
    requestorMobile: MOBILE,
    purpose: "Travel-Related (Airport Transfers)",
    details:
      "Client meeting moved to a video call; the transfer is no longer needed.",
    pickupLocation: "GLS Tower lobby",
    dropoffLocation: "AGT Building",
    towerHead: null,
    vendor: null,
    costPhp: null,
    passengers: PICKUP_PASSENGERS,
    driver: null,
    van: null,
    actedBy: "Buenaflor, Zara",
    actedAt: ACTED_AT,
    modified: false,
    rejectionReason: null,
    // The fixture never displayed one, but the CHECK requires it.
    cancellationReason: "Requestor no longer needs the trip.",
  },
  {
    key: "REQ-1044",
    mode: "pickup",
    status: "Pending",
    site: "Manila",
    submittedAt: "2026-07-28T00:55:00Z",
    startDate: "2026-08-12",
    startTime: "07:15",
    endDate: null,
    endTime: null,
    requestor: "Dizon, Marco",
    requestorMobile: MOBILE,
    purpose: "Travel-Related (Airport Transfers)",
    details: "Escorting a vendor rep to the terminal for a 07:15 departure.",
    pickupLocation: "GLS Tower lobby",
    dropoffLocation: "AGT Building",
    towerHead: null,
    vendor: null,
    costPhp: null,
    passengers: PICKUP_PASSENGERS,
    driver: null,
    van: null,
    actedBy: null,
    actedAt: null,
    modified: false,
    rejectionReason: null,
    cancellationReason: null,
  },
  {
    key: "REQ-1040",
    mode: "pickup",
    status: "Rejected",
    site: "Manila",
    submittedAt: "2026-07-24T03:30:00Z",
    startDate: "2026-08-02",
    startTime: "17:30",
    endDate: null,
    endTime: null,
    requestor: "Jimera, Arielle",
    requestorMobile: MOBILE,
    purpose: "Travel-Related (Airport Transfers)",
    details: "Late transfer for a guest arriving on a rebooked evening flight.",
    pickupLocation: "GLS Tower lobby",
    dropoffLocation: "AGT Building",
    towerHead: null,
    vendor: null,
    costPhp: null,
    passengers: PICKUP_PASSENGERS,
    driver: null,
    van: null,
    actedBy: "Cruz, Ivan",
    actedAt: ACTED_AT,
    modified: false,
    rejectionReason: "No van available on that date.",
    cancellationReason: null,
  },
  {
    key: "REQ-1038",
    mode: "standby",
    status: "Approved",
    site: "Manila",
    submittedAt: "2026-07-22T07:15:00Z",
    startDate: "2026-08-09",
    startTime: "10:00",
    endDate: "2026-08-09",
    endTime: "13:00",
    requestor: "Reyes, Kaye",
    requestorMobile: MOBILE,
    purpose: "Others",
    details: "Standby coverage for an all-day offsite training session.",
    pickupLocation: "GLS Tower lobby",
    dropoffLocation: null,
    towerHead: "Abanto, Norlyn",
    vendor: "Metro Fleet Services",
    costPhp: 6400,
    passengers: STANDBY_PASSENGERS,
    driver: "Ocampo, Dennis",
    van: "VAN-002",
    actedBy: "Abanto, Norlyn",
    actedAt: ACTED_AT,
    modified: false,
    rejectionReason: null,
    cancellationReason: null,
  },
  {
    key: "REQ-1031",
    mode: "standby",
    status: "Pending",
    site: "Iloilo",
    submittedAt: "2026-07-18T05:00:00Z",
    startDate: "2026-07-30",
    startTime: "07:00",
    endDate: "2026-07-30",
    endTime: "17:00",
    requestor: "Salcedo, Liza",
    requestorMobile: MOBILE,
    purpose: "Others",
    details: "Standby coverage for a full-day site inspection.",
    pickupLocation: "AGT Tower lobby",
    dropoffLocation: null,
    towerHead: "Abanto, Norlyn",
    vendor: "Metro Fleet Services",
    costPhp: 6400,
    passengers: STANDBY_PASSENGERS,
    driver: null,
    van: null,
    actedBy: null,
    actedAt: null,
    modified: true,
    rejectionReason: null,
    cancellationReason: null,
  },
  {
    key: "REQ-1025",
    mode: "standby",
    status: "Approved",
    site: "Manila",
    submittedAt: "2026-07-11T01:45:00Z",
    startDate: "2026-08-15",
    startTime: "13:00",
    endDate: "2026-08-15",
    endTime: "15:00",
    requestor: "Jimera, Arielle",
    requestorMobile: MOBILE,
    purpose: "Others",
    details: "Standby coverage for a two-hour executive client visit.",
    pickupLocation: "GLS Tower lobby",
    dropoffLocation: null,
    towerHead: "Abanto, Norlyn",
    vendor: "Metro Fleet Services",
    costPhp: 6400,
    passengers: STANDBY_PASSENGERS,
    driver: "Villanueva, Rey",
    van: "VAN-001",
    actedBy: "Buenaflor, Zara",
    actedAt: ACTED_AT,
    modified: false,
    rejectionReason: null,
    cancellationReason: null,
  },
] as const;
