/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminWhitelist {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  domain_id: string | null;
  email: string | null;
  full_name: string;
  id: Generated<string>;
  notify: Generated<boolean>;
  site: string;
  super_admin: Generated<boolean>;
}

export interface Drivers {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mobile: string;
  name: string;
  shift: string | null;
  site: string;
  updated_at: Generated<Timestamp>;
}

export interface NotificationEvents {
  body: string;
  created_at: Generated<Timestamp>;
  event: string;
  id: Generated<string>;
  link: string;
  read_at: Timestamp | null;
  recipient_user_id: string | null;
  reservation_id: string | null;
  title: string;
}

export interface NotificationOutbox {
  attempts: Generated<number>;
  cc: Generated<Json>;
  created_at: Generated<Timestamp>;
  event_id: string;
  id: Generated<string>;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  payload: Json;
  provider_message_id: string | null;
  recipient: string;
  sent_at: Timestamp | null;
  status: Generated<string>;
  template: string;
}

export interface ReferenceCounters {
  next_value: number;
  year: number;
}

export interface ReservationEvents {
  actor_name: string | null;
  actor_role: string | null;
  actor_user_id: string | null;
  changes: Json | null;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  remark: string | null;
  reservation_id: string;
}

export interface ReservationPassengers {
  domain_id: string;
  id: Generated<string>;
  name: string;
  position: number;
  reservation_id: string;
}

export interface Reservations {
  approving_tower_head: string | null;
  assigned_driver_id: string | null;
  assigned_van_id: string | null;
  cancellation_reason: string | null;
  cancelled_by_role: string | null;
  cost_php: number | null;
  created_at: Generated<Timestamp>;
  details: string;
  dropoff_location: string | null;
  end_at: Timestamp | null;
  id: Generated<string>;
  pickup_location: string;
  purpose: string;
  reference_no: string;
  rejection_reason: string | null;
  rental_car_type: string | null;
  rental_driver_mobile: string | null;
  rental_driver_name: string | null;
  rental_plate: string | null;
  rental_van_number: string | null;
  requestor_email: string;
  requestor_mobile: string;
  requestor_name: string;
  requestor_user_id: string;
  ride_mode: string;
  site: string;
  start_at: Timestamp;
  status: string;
  updated_at: Generated<Timestamp>;
  vendor: string | null;
  version: Generated<number>;
}

export interface RosterEvents {
  actor_name: string;
  actor_role: string;
  actor_user_id: string | null;
  changes: Json | null;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  target_id: string;
  target_table: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  domain_id: string;
  email: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  mobile_number: string | null;
  name: string;
  role: string;
  updated_at: Generated<Timestamp>;
}

export interface Vans {
  active: Generated<boolean>;
  car_type: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  plate: string;
  site: string;
  updated_at: Generated<Timestamp>;
  van_number: string;
}

export interface DB {
  admin_whitelist: AdminWhitelist;
  drivers: Drivers;
  notification_events: NotificationEvents;
  notification_outbox: NotificationOutbox;
  reference_counters: ReferenceCounters;
  reservation_events: ReservationEvents;
  reservation_passengers: ReservationPassengers;
  reservations: Reservations;
  roster_events: RosterEvents;
  users: Users;
  vans: Vans;
}
